// swift-tools-version: 5.9
// Generated by scripts/generate.mjs. Edit plugin-owned swift-targets.swift files.
import PackageDescription
import Foundation

// Plugins compile against the header-only MapLibrePluginApi product of the
// plugin-enabled MapLibre iOS distribution. Applications add its MapLibre product.
// Set MAPLIBRE_IOS_PATH to a local checkout of that package to test unreleased builds.
let mapLibreIOSDependency: Package.Dependency
let mapLibreIOSPackage: String
if let path = ProcessInfo.processInfo.environment["MAPLIBRE_IOS_PATH"] {
    mapLibreIOSDependency = .package(path: path)
    mapLibreIOSPackage = URL(fileURLWithPath: path).standardizedFileURL.lastPathComponent
} else {
    mapLibreIOSDependency = .package(url: "https://github.com/louwers/maplibre-ios-with-plugin-api", exact: "7.0.0-pre1")
    mapLibreIOSPackage = "maplibre-ios-with-plugin-api"
}

let package = Package(
    name: "MapLibreNativePlugins",
    platforms: [.iOS("15.5")],
    products: [
        .library(name: "NgonLayer", targets: ["NgonLayer"]),
        .library(name: "RectangleLayer", targets: ["RectangleLayer"]),
    ],
    dependencies: [mapLibreIOSDependency],
    targets: [
        .target(
        name: "NgonLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: mapLibreIOSPackage)],
        path: "plugins/ngon-layer",
        exclude: [
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests", "scripts", "tests", "release.json", "build.gradle.kts",
        ],
        sources: [
        "ios/src/NgonLayer.mm",
        "shared/cpp/ngon_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_NGON_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
        .target(
        name: "RectangleLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: mapLibreIOSPackage)],
        path: "plugins/rectangle-layer",
        exclude: [
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests",
        ],
        sources: [
        "ios/src/RectangleLayer.mm",
        "shared/cpp/rectangle_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_RECTANGLE_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
