// Generated by scripts/generate.mjs; do not edit.
#import "PluginCatalog.h"
#import <NgonLayer/NgonLayer.h>
#import <RectangleLayer/RectangleLayer.h>
BOOL RegisterGalleryPlugins(NSError **error) {
    if (![MLNNgonLayerPlugin registerPluginWithError:error]) return NO;
    if (![MLNRectangleLayerPlugin registerPluginWithError:error]) return NO;
    return YES;
}
NSArray<NSDictionary *> *GalleryScenes(void) {
    return @[
        @{ @"key": @"ngon", @"title": @"Capital Atlas", @"style": @"ngon-style", @"camera": @[@48.8566, @2.3522, @20000, @0, @0] },
        @{ @"key": @"rectangle", @"title": @"Rectangle layer", @"style": @"rectangle-style", @"camera": @[@48.8566, @2.3522, @20000, @0, @0] },
    ];
}
