// Generated by scripts/generate.mjs; do not edit.
package org.maplibre.plugins.demo;

final class PluginCatalog {
  static void registerAll() {
    org.maplibre.plugins.ngon.NgonLayerPlugin.register();
    org.maplibre.plugins.rectangle.RectangleLayerPlugin.register();
  }
  static final class Entry {
    final String title, description;
    final Class<? extends android.app.Activity> activity;
    Entry(String title, String description, Class<? extends android.app.Activity> activity) {
      this.title = title; this.description = description; this.activity = activity;
    }
  }
  static final Entry[] ENTRIES = {
    new Entry("Capital Atlas", "Explore OpenFreeMap capitals with data-driven n-gons", org.maplibre.plugins.demo.NgonDemoActivity.class),
    new Entry("Rectangle layer", "Feature-driven colors, strokes, and smooth zoom interpolation", org.maplibre.plugins.demo.RectangleDemoActivity.class),
  };
  private PluginCatalog() {}
}
