import {existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync} from 'node:fs';
import {resolve, dirname, relative, isAbsolute} from 'node:path';
import {fileURLToPath} from 'node:url';

const identifier = /^[A-Za-z_][A-Za-z0-9_]*$/;
const qualified = /^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/;
const quoted = JSON.stringify;
function requireValue(condition, message) { if (!condition) throw new Error(message); }
function ownedFile(base, path) {
  requireValue(typeof path === 'string' && !isAbsolute(path), 'Expected a relative plugin-owned path');
  const full = resolve(base, path);
  requireValue(!relative(base, full).startsWith('..') && existsSync(full), `Missing or escaping plugin file: ${path}`);
  return full;
}

export function mapLibreIOSVersion(root) {
  const version = readFileSync(resolve(root, 'maplibre-ios-version.txt'), 'utf8').trim();
  requireValue(/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version), 'Invalid maplibre-ios-version.txt');
  return version;
}

export function discover(root) {
  const directory = resolve(root, 'plugins');
  if (!existsSync(directory)) return [];
  const names = readdirSync(directory, {withFileTypes:true}).filter(e => e.isDirectory() && !e.name.startsWith('.')).map(e => e.name).sort();
  const products = new Set(['MapLibre', 'MapLibrePluginApi']);
  const scenes = new Set();
  return names.flatMap(name => {
    const base = resolve(directory, name), file = resolve(base, 'plugin.json');
    if (!existsSync(file)) {
      requireValue(!existsSync(resolve(base,'build.gradle.kts')) && !existsSync(resolve(base,'swift-targets.swift')),
        `${name}: add plugin.json before generating configuration`);
      return [];
    }
    requireValue(/^[a-z][a-z0-9-]*$/.test(name), `Invalid plugin directory: ${name}`);
    const config = JSON.parse(readFileSync(file,'utf8'));
    requireValue(config.schemaVersion === 1, `${name}: unsupported metadata schema`);
    if (config.android) {
      requireValue(qualified.test(config.android.registrationClass), `${name}: invalid Android registration class`);
      ownedFile(base,'build.gradle.kts');
    }
    if (config.apple) {
      const apple = config.apple;
      requireValue(identifier.test(apple.product) && identifier.test(apple.registrationClass), `${name}: invalid Apple identifiers`);
      requireValue(/^[A-Za-z0-9_]+\/[A-Za-z0-9_]+\.h$/.test(apple.header), `${name}: invalid Apple header`);
      const targets = readFileSync(ownedFile(base,apple.targets),'utf8');
      let hasProduct = false;
      for (const match of targets.matchAll(/\.target\(\s*name:\s*"([^"]+)"/g)) {
        requireValue(!products.has(match[1]), `${name}: duplicate Swift target ${match[1]}`);
        products.add(match[1]);
        hasProduct ||= match[1] === apple.product;
      }
      requireValue(hasProduct, `${name}: product target missing from Swift fragment`);
      config.swiftTargets = targets;
    }
    if (config.demo) {
      requireValue(typeof config.demo.title === 'string' && config.demo.title.length > 0, `${name}: demo title required`);
      if (config.demo.androidActivity) {
        requireValue(config.android && qualified.test(config.demo.androidActivity), `${name}: invalid Android demo`);
        ownedFile(base, 'examples/android/java/' + config.demo.androidActivity.replaceAll('.','/') + '.java');
      }
      if (config.demo.ios) {
        const demo=config.demo.ios;
        requireValue(config.apple && /^[a-z0-9-]+$/.test(demo.key) && !scenes.has(demo.key), `${name}: invalid or duplicate scene key`);
        scenes.add(demo.key);
        requireValue(Array.isArray(demo.camera) && demo.camera.length === 5 && demo.camera.every(Number.isFinite), `${name}: camera needs five finite numbers`);
        ownedFile(base,`examples/android/assets/${demo.style}.json`);
      }
    }
    return [{...config, name, base, renderTests:existsSync(resolve(base,'render-tests/manifest.json')), release:existsSync(resolve(base,'release.json'))}];
  });
}

export function render(root) {
  const plugins=discover(root), apple=plugins.filter(p=>p.apple), android=plugins.filter(p=>p.android);
  const androidDemos=android.filter(p=>p.demo?.androidActivity), iosDemos=apple.filter(p=>p.demo?.ios);
  const outputs=new Map();
  outputs.set('Package.swift', `// swift-tools-version: 5.9
// Generated by scripts/generate.mjs. Edit plugin-owned swift-targets.swift files.
import PackageDescription
import Foundation

// Plugins compile against the header-only MapLibrePluginApi product of the
// plugin-enabled MapLibre iOS distribution. Applications add its MapLibre product.
// Set MAPLIBRE_IOS_PATH to a local checkout of that package to test unreleased builds.
let mapLibreIOSDependency: Package.Dependency
let mapLibreIOSPackage: String
if let path = ProcessInfo.processInfo.environment["MAPLIBRE_IOS_PATH"] {
    mapLibreIOSDependency = .package(path: path)
    mapLibreIOSPackage = URL(fileURLWithPath: path).standardizedFileURL.lastPathComponent
} else {
    mapLibreIOSDependency = .package(url: "https://github.com/louwers/maplibre-ios-with-plugin-api", exact: "${mapLibreIOSVersion(root)}")
    mapLibreIOSPackage = "maplibre-ios-with-plugin-api"
}

let package = Package(
    name: "MapLibreNativePlugins",
    platforms: [.iOS("15.5")],
    products: [
${apple.map(p=>`        .library(name: ${quoted(p.apple.product)}, targets: [${quoted(p.apple.product)}]),`).join('\n')}
    ],
    dependencies: [mapLibreIOSDependency],
    targets: [
${apple.map(p=>p.swiftTargets.trim().split('\n').map(l=>'        '+l.trimStart()).join('\n')).join('\n')}
    ],
    cxxLanguageStandard: .cxx20
)
`);
  outputs.set('examples/ios-app/App/PluginCatalog.h', `// Generated by scripts/generate.mjs; do not edit.
#import <Foundation/Foundation.h>
BOOL RegisterGalleryPlugins(NSError **error);
NSArray<NSDictionary *> *GalleryScenes(void);
`);
  outputs.set('examples/ios-app/App/PluginCatalog.m', `// Generated by scripts/generate.mjs; do not edit.
#import "PluginCatalog.h"
${apple.map(p=>`#import <${p.apple.header}>`).join('\n')}
BOOL RegisterGalleryPlugins(NSError **error) {
${apple.map(p=>`    if (![${p.apple.registrationClass} registerPluginWithError:error]) return NO;`).join('\n')}
    return YES;
}
NSArray<NSDictionary *> *GalleryScenes(void) {
    return @[
${iosDemos.map(p=>{const d=p.demo.ios;return `        @{ @"key": @${quoted(d.key)}, @"title": @${quoted(p.demo.title)}, @"style": @${quoted(d.style)}, @"camera": @[${d.camera.map(n=>'@'+n).join(', ')}] },`;}).join('\n')}
    ];
}
`);
  outputs.set('examples/android-app/app/src/main/java/org/maplibre/plugins/demo/PluginCatalog.java', `// Generated by scripts/generate.mjs; do not edit.
package org.maplibre.plugins.demo;

final class PluginCatalog {
  static void registerAll() {
${android.map(p=>`    ${p.android.registrationClass}.register();`).join('\n')}
  }
  static final class Entry {
    final String title, description;
    final Class<? extends android.app.Activity> activity;
    Entry(String title, String description, Class<? extends android.app.Activity> activity) {
      this.title = title; this.description = description; this.activity = activity;
    }
  }
  static final Entry[] ENTRIES = {
${androidDemos.map(p=>`    new Entry(${quoted(p.demo.title)}, ${quoted(p.demo.description||'')}, ${p.demo.androidActivity}.class),`).join('\n')}
  };
  private PluginCatalog() {}
}
`);
  outputs.set('examples/android-app/app/src/main/AndroidManifest.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate.mjs; do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:name=".DemoApplication" android:allowBackup="false"
        android:label="@string/app_name" android:supportsRtl="true" android:theme="@style/AppTheme">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
${androidDemos.map(p=>`        <activity android:name="${p.demo.androidActivity}" android:exported="false" />`).join('\n')}
    </application>
</manifest>
`);
  const template=readFileSync(resolve(root,'scripts/templates/release-plugin.yml'),'utf8');
  requireValue(template.includes('@@PLUGIN_OPTIONS@@'),'Release template missing plugin placeholder');
  const release=plugins.filter(p=>p.release).map(p=>p.name);
  outputs.set('.github/workflows/release-plugin.yml', '# Generated by scripts/generate.mjs; edit scripts/templates/release-plugin.yml.\n'+template.replace('@@PLUGIN_OPTIONS@@',(release.length?release:['no-plugins']).map(n=>'          - '+n).join('\n')));
  return outputs;
}

export function generate(root, check=false) {
  // Validate and render everything before writing any files.
  const outputs=render(root), stale=[];
  for(const [path,content] of outputs) {
    const file=resolve(root,path);
    if(existsSync(file) && readFileSync(file,'utf8')===content)continue;
    stale.push(path);
    if(!check){mkdirSync(dirname(file),{recursive:true});writeFileSync(file,content);}
  }
  if(check && stale.length)throw new Error('Generated configuration is stale. Run node scripts/generate.mjs:\n'+stale.join('\n'));
  return stale;
}

if(process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  try {
    requireValue(process.argv.slice(2).every(arg=>arg==='--check'),'Usage: node scripts/generate.mjs [--check]');
    const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
    const changed=generate(root,process.argv.includes('--check'));
    console.log(`Plugin configuration ${process.argv.includes('--check')?'checked':'generated'} (${changed.length} changed files).`);
  } catch(error) { console.error(error.message); process.exitCode=1; }
}
